### ISSUE TITLE
Problem "SyntaxError: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by Danielejava** [llangit/instagram-liked-posts-downloader#3]
Hi, I'm trying to run your code on a Mac via Terminal. I have no idea of how codes work and I keep getting this message:

`Querying posts...
/Users/mac/node_modules/request-promise-core/lib/plumbing.js:130
            throw thrownException;
            ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._rp_callbackOrig (/Users/mac/Downloads/instagram-liked-posts-downloader-master/instaload.js:105:25)
    at Request.plumbing.callback (/Users/mac/node_modules/request-promise-core/lib/plumbing.js:76:39)
    at Request.RP$callback [as _callback] (/Users/mac/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/mac/node_modules/request/request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (/Users/mac/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:196:13)
    at IncomingMessage.<anonymous> (/Users/mac/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:284:20)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
Macintosh:instagram-liked-posts-downloader-master mac$ `

How can I fix this?

**Comment by llangit** [comment]
Hi,

Instagram must've changed something in their API, to which there seems to be no quick fix.
I'd have to investigate a new way to download the posts. Unfortunately, I'm very busy with other projects at the moment.

In the meantime, please have a look at these Instagram downloader extensions for Chrome:
https://chrome.google.com/webstore/detail/downloader-for-instagram/olkpikmlhoaojbbmmpejnimiglejmboe
https://chrome.google.com/webstore/detail/downloader-for-instagram/mhobbbccfdlpigiikcnobledcncomamb
https://chrome.google.com/webstore/detail/downloader-for-instagram/dhchoilkelgbblajmpbhpofhheecgkhh
Note that these extensions download all posts from a given profile, not just liked posts.

@ Developers: if you know a fix, feel free to contribute!

**Comment by MarkPTP** [comment]
You should update the readme to let people know this currently doesn't work
